#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
#runApplication refineMesh -overwrite
touch test-initAlphaField.ansys
restore0Dir
runApplication setAlphaField
#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar

#------------------------------------------------------------------------------
