/*---------------------------------------------------------------------------*\
Description
    Compatibility include

    ansysVtkUIndPatchWriter.H combined into ansysVtkIndPatchWriter.H (MAY-2022)

\*---------------------------------------------------------------------------*/

#ifndef Foam_vtk_UIndPatchWriter_H
#define Foam_vtk_UIndPatchWriter_H

#include "ansysVtkIndPatchWriter.H"

#endif

// ************************************************************************* //
