/*---------------------------------------------------------------------------*\
Description
    Compatibility include

    ansysVtkUIndPatchGeoFieldsWriter.H
    combined into ansysVtkIndPatchGeoFieldsWriter.H
    (MAY-2022)

\*---------------------------------------------------------------------------*/

#ifndef Foam_vtk_UIndPatchGeoFieldsWriter_H
#define Foam_vtk_UIndPatchGeoFieldsWriter_H

#include "ansysVtkIndPatchGeoFieldsWriter.H"

#endif

// ************************************************************************* //
